### ISSUE TITLE
在K8S里部署apollo微服务配置中心，定义dev，pro，uat，fat 4种环境

### ISSUE THREAD

**Issue by thm7x** [pypygo/gitbook#45]
官方资料：
https://github.com/ctripcorp/apollo

#### 1. 事先在mysql5.7+ 里创建要求的数据库和表结构，[sql脚本官方找](https://github.com/ctripcorp/apollo/tree/master/scripts/sql)
>1. configdb.sql: dev环境默认库ApolloConfigDB，fat环境ApolloConfigDB_FAT，pro环境ApolloConfigDB_PRO，uta环境ApolloConfigDB_UAT
> 2. portaldb.sql: portal的默认库ApolloPortalDB

#### 2. 编写4种环境的helm yaml值文件
2.1  dev环境helm yaml值文件
数据库默认
```yaml
configdb:
  # apolloconfigdb host
  host: "192.168.200.52"
  # apolloconfigdb user name
  userName: "root"
  # apolloconfigdb password
  password: "123123"
  service:
    # whether to create a Service for this host or not
    enabled: true

configService:
  replicaCount: 1

adminService:
  replicaCount: 1

#bash执行：# helm  install apollo-service-dev ./apollo-service -f apollo-dev-values.yaml -n apollo
```

2.2 pro环境helm yaml值文件
数据库定义ApolloConfigDB_PRO
```yaml
configdb:
  # apolloconfigdb host
  host: "192.168.200.52"
  dbName: ApolloConfigDB_PRO
  # apolloconfigdb user name
  userName: "root"
  # apolloconfigdb password
  password: "123123"
  service:
    # whether to create a Service for this host or not
    enabled: true

configService:
  replicaCount: 1

adminService:
  replicaCount: 1

#bash执行：# helm  install apollo-service-pro ./apollo-service -f apollo-pro-values.yaml -n apollo
```
2.3 uat环境helm yaml值文件
数据库定义ApolloConfigDB_UAT
```yaml
configdb:
  # apolloconfigdb host
  host: "192.168.200.52"
  dbName: ApolloConfigDB_UAT
  # apolloconfigdb user name
  userName: "root"
  # apolloconfigdb password
  password: "123123"
  service:
    # whether to create a Service for this host or not
    enabled: true

configService:
  replicaCount: 1

adminService:
  replicaCount: 1

#bash执行：# helm  install apollo-service-uat ./apollo-service -f apollo-uat-values.yaml -n apollo
```

2.4 fat环境 helm yaml值文件
数据库定义ApolloConfigDB_FAT
```yaml
configdb:
  # apolloconfigdb host
  host: "192.168.200.52"
  dbName: ApolloConfigDB_FAT
  # apolloconfigdb user name
  userName: "root"
  # apolloconfigdb password
  password: "123123"
  service:
    # whether to create a Service for this host or not
    enabled: true

configService:
  replicaCount: 1

adminService:
  replicaCount: 1

#bash执行：# helm  install apollo-service-fat ./apollo-service -f apollo-fat-values.yaml -n apollo
```
2.5 portal helm yaml值文件
数据库默认
```yaml
replicaCount: 1
service:
  type: LoadBalancer
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ""
      paths: []
  tls: []

config:
  # specify the env names, e.g. dev,pro
  envs: "dev,pro,fat,uat"
  # specify the meta servers, e.g.
  # dev: http://apollo-configservice-dev:8080
  # pro: http://apollo-configservice-pro:8080
  metaServers:
    dev: http://apollo-service-dev-apollo-configservice:8080
    pro: http://apollo-service-pro-apollo-configservice:8080
    fat: http://apollo-service-fat-apollo-configservice:8080
    uat: http://apollo-service-uat-apollo-configservice:8080

portaldb:
  # apolloportaldb host
  host: "192.168.200.52"
  dbName: ApolloPortalDB
  # apolloportaldb user name
  userName: root
  # apolloportaldb password
  password: "123123"

#bash执行：# helm  install apollo-portal apollo-portal/ -f portal-values.yaml -n apollo
```

#### 3. 查看确定的loadBalancer地址
可以在K8S的dashboard查看服务部署情况，需要几分钟
```shell
data@data:~/goproject/dev-ops/apollo_install$ export SERVICE_IP=$(kubectl get svc --namespace apollo apollo-portal --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
data@data:~/goproject/dev-ops/apollo_install$ echo http://$SERVICE_IP:8070
***http://192.168.80.203:8070***
```
#### 4. 使用loadBalancer访问K8S里的apollo
![image](https://user-images.githubusercontent.com/35193505/94124811-11735580-fe88-11ea-8d6b-beeba0b4f0f7.png)
